import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { SideBar } from "@/app/_components/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ask your file - RAG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SideBar />
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <div className="flex p-8 justify-end">
            <UserButton
              appearance={{
                elements: {
                  userButtonAvatarBox: "size-10",
                },
              }}
            />
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
